diegomura/react-pdf-site

- pages/index.js
This PR fixes a missing `href` attribute, to link the "try it out" button in the index page to the actual playground.
> Fix missing "Try it out!" button target on index page

- docs/on-the-fly.md
Since the `BlobProvider` render function is calling `return <div>...`, it needs to use curly braces instead of parens
> Fix function brackets in BlobProvider example

- docs/image.md
- docs/link.md
- docs/note.md
- docs/text.md
- docs/view.md
There was a number of dead links on the https://react-pdf.org/components page. This PR corrects the links to point to the correct Advanced link.
@diegomura
> Update links to advanced topics for components

- docs/image.md
- Also documents that Image src can take an object containing image data
- Documents the `safePath` and `allowDangerousPaths` props
Documents diegomura/react-pdf#457
> Reflect that Image src can take local path on Node

- docs/on-the-fly.md
In *Advanced* part, PDFDownloadLink receive `document` prop as `MyDoc` instead of `<MyDoc />`.
> PDFDownloadLink - Clarify `document` prop's usage

- docs/fonts.md
This tripped me up for a while, then I found this issue raised on the main repo: https://github.com/diegomura/react-pdf/issues/417.
Looks like this part of the documentation was just missed when the docs were updated with the change to `registerHyphenationCallback`.
> Update documentation example for disabling hyphenation

- docs/advanced.md
- docs/webpack.md
- src/components/Menu.js
Some additional info on how to fix a custom webpack config in order for react-pdf to work.
I noticed that react-pdf would build fine in create-react-app, but not in next.js, so I dug into CRA-scripts and found that config setting.
> webpack settings

- docs/canvas.md
- docs/components.md
- docs/debugging.md
- docs/document.md
- docs/dynamic-content.md
- docs/fonts.md
- docs/hyphenation.md
- docs/image.md
- docs/note.md
- docs/page-wrapping.md
- docs/page.md
- docs/rendering-process.md
- docs/ruler.md
- docs/styling.md
- docs/text.md
By profession, I'm a web developer, but a hobbyist teacher (teach English as primary subject) too. Nowadays, learning about react-pdf usage. I encountered some grammatical errors and typos in site docs, so I decided to fix them to contribute to the open-source best pdf-generator package. I proof-read twice after spending 2 hours and now it's corrected. A few other things need to be fixed, which will be done later.
> fixed typos and corrected grammatical errors

- docs/orphan-widow-protection.md
Not only is this mnemonic unnecessary, it literally says "an orphan has no past" and "a widow has no future". It should be clear that these are both incorrect and offensive.
> Remove unnecessary mnemonic

- docs/components.md
1. Add `Buffer` to valid props of Image, which is in fact [valid](https://github.com/diegomura/react-pdf/blob/66d6259971e99846602d69de85fcbba98825d608/packages/types/image.d.ts#L11-L15).
2. Remove char `\` from example column.
> Add Buffer to valid props of Image component

- docs/fonts.md
The website is missing details on what fonts are available by default. 
This PR adds a list of available fonts derived from [this issue](https://github.com/diegomura/react-pdf/issues/402#issuecomment-443347283).
> Add list of builtin fonts

- src/components/Repl/PDFViewer.js
This PR adds a second `<Document />` component when PdfViewer detects that the new value is being either still being converted by react-pdf/renderer or being rendered by React-PDF.
I used React-PDF's `<Page />`'s `onRenderSuccess` prop to inform PdfViewer that the PDF has been fully rendered. It does this by setting previously rendered PDF blob URL to component's state.
The second `<Document />` component holds previous blob URL, while the "main" `<Document />`, as before, holds the latest value at all times.
By manually managing `key` props, React prevents updates to whatever component renders previous value, keeping it visible on the screen while the new one is loading.
> feat: show previous PDF document while the next one is being created & rendered

- docs/advanced.md
- docs/components.md
- docs/document-navigation.md
- src/components/Layout/Menu.js
This is a solution to an (non-)issue I've filed in the main `react-pdf` repo: diegomura/react-pdf#2110
1. Added proper [Named Destinations](https://pdfkit.org/docs/destinations.html) documentation with an example
2. Combined **Destinations** and **Bookmarks** sections in **Advanced** page into a single section called **Document Navigation**
3. Renamed and changed **Bookmarks** page link in `Menu` to **Document Navigation**
4. Added `id` prop to `Page`, `View`, and `Text` elements in **Components** page (as per [types](https://github.com/diegomura/react-pdf/tree/master/packages/types))
5. Added destination name to `Link`'s `src` prop definition in **Components** page
> feat: proper documentation of Named Destinations

- docs/components.md
- docs/document-navigation.md
Related to diegomura/react-pdf-site#102
1. Fixed my initial confusion over where the leading hash goes
2. Fixed the same mistake in the components page, made wording clearer
> fix: leading hash mistake in destination section, better wording

- docs/node.md
> fix: couple of typos in node.md

- docs/svg.md
Text anchor is horizontal alignment, dominant baseline controls vertical alignment.
> fix: textAnchor description in SVG documentation

- docs/svg.md
In relation to this PR https://github.com/diegomura/react-pdf/pull/2363, it looks like the `strokeLinejoin` was not added to the documentation.
> docs: add strokeLinejoin to SVG Presentation attributes

- docs/hyphenation.md
Fixes the id in the hyphenation callback link to correctly route.
Old link: https://react-pdf.org/fonts#registerHyphenationCallback
New link: https://site-git-fork-bdkopen-fix-hyphentation-callback-link-diegomura.vercel.app/fonts#registerhyphenationcallback
> fix: make hyphenation callback id lowercase

- docs/compatibility.md
- docs/quick-start.md
- docs/rendering-process.md
- pages/compatibility.js
- src/components/Layout/Menu.js
This commit adds Compatibility page, outlining supported Node.js versions, React versions, Next.js versions (and workarounds for older versions), and esbuild in ESM mode.
Closes https://github.com/diegomura/react-pdf/issues/2569
> feat: add Compatibility page

- docs/fonts.md
Thanks for react-pdf, amazing library!
Quick PR to update the support to also allow WOFF fonts - we have confirmed support for WOFF fonts, as other users also have over here:
- https://github.com/diegomura/react-pdf/issues/334#issuecomment-1748669840
> Add support for WOFF fonts

- examples/font-register.txt
- Fixes the file paths for the font example
Deployment preview: https://site-7bsx-git-fork-bdkopen-fi-7f61a9-diego-muraccioles-projects.vercel.app/repl?example=font-register
Resolves issue: https://github.com/diegomura/react-pdf/issues/2879
> Fix: Correct Font File Path Repl Example
